env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:vue/vue3-essential
  - "@unocss"
parserOptions:
  ecmaVersion: latest
  parser: "@typescript-eslint/parser"
  sourceType: module
plugins:
  - "@typescript-eslint"
  - vue
ignorePatterns:
  - node_modules
  - dist
rules: { "prettier/prettier": "off" }
